# Generated by Django 4.1.7 on 2023-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='description',
        ),
        migrations.AddField(
            model_name='carousel',
            name='title1',
            field=models.CharField(max_length=300, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='carousel',
            name='title2',
            field=models.CharField(max_length=300, null='True'),
            preserve_default='True',
        ),
    ]
